#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Pinned catalogs, honest development fallback coverage and generated allowlist."""
from pathlib import Path
import copy,hashlib,json,re,sys,xml.etree.ElementTree as ET
ROOT=Path(__file__).resolve().parents[1]; DIR=ROOT/'gui/i18n'
def inputs():
 payload=(DIR/'locales.json').read_bytes()
 assert hashlib.sha256(payload).hexdigest()=='11eef3ecb89db19b7cadc88400e5ab4978b8af15263af63d2b0ecfa5a4463919','Pinned workspace inventory changed'
 manifest=json.loads(payload)
 locales=[v['synapseId'] for v in manifest['locales']]
 assert manifest['schema']=='synapse.i18n.locales/v1' and len(locales)==len(set(locales))==64
 assert all(re.fullmatch(r'[a-z]{2,3}(?:_[A-Z]{2})?(?:@[a-z]+)?',s) for s in locales)
 return locales

def header(locales):
 return '// SPDX-License-Identifier: MIT\n// Generated by tools/catalogs.py; pinned package-owned allowlist.\n'+'static constexpr const char *kMonitorLocales[] = {\n'+''.join(f'    "{s}",\n' for s in locales)+'};\n'

def generate():
 locales=inputs(); base=ET.parse(DIR/'synapse-monitor_en_US.ts').getroot()
 coverage={}
 for loc in locales:
  if loc not in {'en_US','it_IT'}:
   p=DIR/f'synapse-monitor_{loc}.ts'
   if p.exists():raise ValueError('Refusing to overwrite existing catalog: '+loc)
   root=copy.deepcopy(base);root.set('language',loc)
   for msg in root.findall('.//message'):
    ET.SubElement(msg,'extracomment').text='Development fallback: en_US; not a reviewed translation.'
   ET.indent(root,space='  ')
   p.write_text('<?xml version="1.0" encoding="utf-8"?>\n<!-- SPDX-License-Identifier: MIT -->\n<!DOCTYPE TS>\n'+ET.tostring(root,encoding='unicode')+'\n')
  n=len(base.findall('.//message'))
  coverage[loc]={'authored':n if loc in {'en_US','it_IT'} else 0,'fallback':0 if loc in {'en_US','it_IT'} else n}
 (DIR/'coverage.json').write_text(json.dumps({'schema':'synapse.monitor.catalog-coverage/v1','productionComplete':False,'reviewedLocales':['en_US','it_IT'],'catalogs':coverage},indent=2)+'\n')
 (ROOT/'gui/locales.inc').write_text(header(locales))

def check():
 locales=inputs();coverage=json.loads((DIR/'coverage.json').read_text())
 assert coverage['productionComplete'] is False and coverage['reviewedLocales']==['en_US','it_IT']
 assert set(coverage['catalogs'])==set(locales)
 assert {p.stem.removeprefix('synapse-monitor_') for p in DIR.glob('*.ts')}==set(locales)
 assert (ROOT/'gui/locales.inc').read_text()==header(locales)
 catalogs={}
 for loc in locales:
  p=DIR/f'synapse-monitor_{loc}.ts';assert p.stat().st_size<256*1024
  root=ET.parse(p).getroot();assert root.get('language')==loc
  messages=root.findall('.//message');assert 0<len(messages)<=512
  ids=[m.get('id') for m in messages];assert len(set(ids))==len(ids)
  assert all(re.fullmatch(r'synapse\.monitor\.[a-z0-9.-]+',s or '') for s in ids)
  texts={}
  for m in messages:
   t=m.find('translation');assert t is not None and t.text and not t.attrib and len(t)==0
   assert m.findtext('source')==m.get('id')
   texts[m.get('id')]=t.text
   if loc not in {'en_US','it_IT'}:assert m.findtext('extracomment')=='Development fallback: en_US; not a reviewed translation.'
  catalogs[loc]=texts
  n=len(messages);assert coverage['catalogs'][loc]=={'authored':n if loc in {'en_US','it_IT'} else 0,'fallback':0 if loc in {'en_US','it_IT'} else n}
 base=catalogs['en_US']
 for loc,texts in catalogs.items():
  assert texts.keys()==base.keys()
  for mid,text in texts.items():
   assert re.findall(r'%L?[0-9]+|%n',text)==re.findall(r'%L?[0-9]+|%n',base[mid]),(loc,mid)
   if loc not in {'en_US','it_IT'}:assert text==base[mid],(loc,mid)
 for p in (ROOT/'gui/qml').glob('*.qml'):
  for mid in re.findall(r'qsTrId\("([^"]+)"\)',p.read_text()):assert mid in base,(p,mid)
 print(f'Catalog coverage: 64 locales, {len(base)} IDs each; 2 authored catalogs, 62 explicit en_US fallbacks. Not production-complete.')
if __name__=='__main__':
 if sys.argv[1:]==['--initialize-fallbacks']:generate()
 elif sys.argv[1:] not in ([],['--check']):raise SystemExit('Expected --check or --initialize-fallbacks')
 check()
