// SPDX-License-Identifier: MIT
#include "monitor.h"

#include <inttypes.h>

void mon_render_stream_metadata(const mon_options *options) {
    if (!options || !options->stream_output) return;
    fputs(",\"stream\":{\"schema\":\"synapse.monitor.stream-frame/v1\"",
          stdout);
    printf(",\"sequence\":%" PRIu64 ",\"intervalMilliseconds\":%" PRIu64,
           options->stream_sequence, options->interval_milliseconds);
    fputc('}', stdout);
}

int mon_render_presentation(void) {
    fputs("{\"schema\":\"synapse.monitor.presentation/v1\","
          "\"readOnly\":true,\"producer\":{"
          "\"id\":\"synapse-monitor\",\"version\":\"" MON_VERSION "\"},"
          "\"formats\":{\"snapshot\":[{"
          "\"id\":\"text\",\"mediaType\":\"text/plain\","
          "\"framing\":\"single-document\"},{"
          "\"id\":\"json\",\"mediaType\":\"application/json\","
          "\"framing\":\"single-object-one-line\"}],"
          "\"stream\":{\"id\":\"ndjson\","
          "\"mediaType\":\"application/x-ndjson\","
          "\"framing\":\"one-complete-object-per-line\","
          "\"payload\":\"complete-view-snapshot\","
          "\"streamMetadataSchema\":\"synapse.monitor.stream-frame/v1\",",
          stdout);
    printf("\"maximumLineBytes\":%zu,\"sequenceStartsAt\":0,",
           MON_STREAM_LINE_MAX);
    fputs("\"backpressure\":\"blocking\",\"errorChannel\":\"stderr\"}},"
          "\"views\":[{"
          "\"id\":\"processes\",\"ordinal\":1,"
          "\"schema\":\"synapse.monitor.snapshot/v1\","
          "\"streamable\":true,"
          "\"filter\":{\"supported\":true,\"maximumBytes\":64,"
          "\"characterSet\":\"printable-ascii\"},"
          "\"sort\":[\"cpu\",\"memory\",\"read\",\"write\","
          "\"name\",\"pid\",\"user\",\"state\",\"threads\"],"
          "\"group\":[\"class\",\"name\",\"none\"],"
          "\"columns\":[\"name\",\"pid\",\"user\",\"state\","
          "\"threads\",\"cpu\",\"memory\",\"read\",\"write\"],"
          "\"defaultColumns\":[\"name\",\"pid\",\"user\",\"cpu\","
          "\"memory\",\"read\",\"write\"],"
          "\"rowIdentity\":[\"pid\",\"startTicks\"]},{"
          "\"id\":\"performance\",\"ordinal\":2,"
          "\"schema\":\"synapse.monitor.performance/v2\","
          "\"streamable\":true,"
          "\"filter\":{\"supported\":false},\"sort\":[],"
          "\"group\":[],\"columns\":[],\"defaultColumns\":[],"
          "\"rowIdentity\":[\"cpu.index\",\"gpus.card\","
          "\"thermals.class+source+label\",\"fans.source+label\","
          "\"disks.name\",\"network.name\"]},{"
          "\"id\":\"services\",\"ordinal\":3,"
          "\"schema\":\"synapse.monitor.services/v1\","
          "\"streamable\":true,"
          "\"filter\":{\"supported\":true,\"maximumBytes\":64,"
          "\"characterSet\":\"printable-ascii\"},"
          "\"sort\":[\"name\",\"description\",\"status\","
          "\"startup\",\"pid\",\"user\",\"executable\"],"
          "\"group\":[],\"columns\":[\"name\",\"description\","
          "\"status\",\"startup\",\"pid\",\"user\","
          "\"executable\"],\"defaultColumns\":[\"name\","
          "\"description\",\"status\",\"startup\",\"pid\","
          "\"user\",\"executable\"],\"rowIdentity\":[\"name\"]},{"
          "\"id\":\"startup\",\"ordinal\":4,"
          "\"schema\":\"synapse.monitor.startup/v1\","
          "\"streamable\":true,"
          "\"filter\":{\"supported\":true,\"maximumBytes\":64,"
          "\"characterSet\":\"printable-ascii\"},"
          "\"sort\":[\"name\",\"publisher\",\"status\",\"type\","
          "\"scope\",\"command\"],\"group\":[],"
          "\"columns\":[\"name\",\"publisher\",\"status\","
          "\"type\",\"location\",\"command\"],"
          "\"defaultColumns\":[\"name\",\"publisher\",\"status\","
          "\"type\",\"location\",\"command\"],"
          "\"rowIdentity\":[\"id\"]},{"
          "\"id\":\"connections\",\"ordinal\":5,"
          "\"schema\":\"synapse.monitor.connections/v1\","
          "\"streamable\":true,"
          "\"filter\":{\"supported\":true,\"maximumBytes\":64,"
          "\"characterSet\":\"printable-ascii\"},"
          "\"sort\":[\"protocol\",\"local\",\"remote\",\"status\","
          "\"pid\",\"process\"],\"group\":[],"
          "\"columns\":[\"protocol\",\"local\",\"remote\","
          "\"state\",\"pid\",\"process\"],"
          "\"defaultColumns\":[\"protocol\",\"local\",\"remote\","
          "\"state\",\"pid\",\"process\"],"
          "\"rowIdentity\":[\"socketInode\"]},{"
          "\"id\":\"information\",\"ordinal\":6,"
          "\"schema\":\"synapse.monitor.information/v1\","
          "\"streamable\":true,"
          "\"filter\":{\"supported\":false},\"sort\":[],"
          "\"group\":[],\"columns\":[],\"defaultColumns\":[],"
          "\"rowIdentity\":[]}],"
          "\"inspection\":{"
          "\"schema\":\"synapse.monitor.process-inspection/v1\","
          "\"identity\":[\"pid\",\"startTicks\"],"
          "\"streamable\":false},"
          "\"sampling\":{\"sampleMilliseconds\":{"
          "\"minimum\":100,\"maximum\":2000,\"default\":250},"
          "\"intervalMilliseconds\":{\"minimum\":250,"
          "\"maximum\":10000,\"default\":1000},"
          "\"rowLimit\":{\"minimum\":1,\"maximum\":512,"
          "\"default\":40}},"
          "\"history\":{\"maximumSamples\":60,"
          "\"ordering\":\"oldest-to-newest\","
          "\"unavailableSample\":null,"
          "\"measuredZeroDistinctFromUnavailable\":true},"
          "\"units\":{\"utilization\":\"milli-percent\","
          "\"memory\":\"bytes\",\"rate\":\"bytes-per-second\","
          "\"temperature\":\"millidegrees-celsius\","
          "\"frequency\":\"hertz\",\"power\":\"microwatts\","
          "\"fan\":\"rpm\",\"uptime\":\"seconds\"},"
          "\"availability\":{\"unavailableNumeric\":null,"
          "\"measuredZero\":0,\"partialRowsRetained\":true},"
          "\"localization\":{\"identifiers\":\"locale-neutral\","
          "\"humanLabelsOwnedByGui\":true},"
          "\"authority\":{\"processMutation\":false,"
          "\"serviceMutation\":false,\"startupMutation\":false,"
          "\"connectionControl\":false,\"gpuControl\":false,"
          "\"thermalControl\":false,\"privilegedHelper\":false,"
          "\"listener\":false,\"telemetry\":false},"
          "\"privacy\":{\"commandLinesExposed\":false,"
          "\"environmentsExposed\":false,\"fullPathsExposed\":false,"
          "\"authenticationCredentialsExposed\":false,"
          "\"serialNumbersExposed\":false,"
          "\"hostNameExposed\":false}}\n", stdout);
    return ferror(stdout) ? 1 : 0;
}
